#use capital letters for keywords and lowecase letters for table rows and column names

#creating a database in sql
#CREATE DATABASE test;
#to remove a database
#DROP DATABASE test;

CREATE DATABASE record_company;
USE record_company;

#creating a table
#CREATE TABLE test(
	#inside here we pass all the columns that our table should have with their datatypes seperated by commas
    #test_column1 INT,
    #test_colums2 VARCHAR(255) #meaning that this will be of string datatype with a maximum of 255 characters
#);

#to add another column inside the test table
#ALTER TABLE test ADD test_column_forgotten_column VARCHAR(255);
#to delete a table,
#DROP TABLE test; #successfully deletes the test table we had created

#creating a bands table with name and id fields where the id is going to be the primary key
CREATE TABLE bands(
	name VARCHAR(255) NOT NULL, #SPECIFYING THAT THIS FIELD CANNOT BE EMPTY
    id INT NOT NULL AUTO_INCREMENT, #specifying that id will be autogenerated and autoincremented, so we don't type id on our own
    PRIMARY KEY(id) #specifying that the id field will be the primary key
);

#creating the albums table, id (autogenerated) name(never null) release year,
CREATE TABLE albums(
	id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    relese_year INT,
    band_id INT NOT NULL, #this is going to reference the bands table
    PRIMARY KEY(id), #specifying that the primary key will be the id
    FOREIGN KEY(band_id) REFERENCES bands(id) #specifying that the band_id will be the foreign key referencing the bands table using id
);

#INSERTING DATA, WE WILL BEGIN WITH THE BANDS TABLE
INSERT INTO bands(name) VALUES ('Sauti Sol');
#that was inserting only one entry, we can also insert many entries
INSERT INTO bands(name) VALUES ('Elani'), ('H-ART the band'), ('The Wanyika'),('Maroon 5');
SELECT * FROM bands;

#we can also specify the limit of eg if we want to get back only two bands
SELECT * FROM bands LIMIT 2;

#we can also select specific columns eg name only
SELECT name from bands;

#we can also change the name of the columns during selecting
SELECT id as 'BAND_ID', name as 'Band Name' FROM bands;

#we can also sort eg alphabetically by name
SELECT * FROM bands ORDER BY name;

#the default for sorting is ascending but we can also change that to descending as shown
SELECT * FROM bands ORDER BY name DESC; #FOR ASCENDING IT IS ASC




